export const COLUMNS = [
  "ERP CODE",
  "location",
  "L2-VALVE TYPE",
  "DIMENSION",
  "L7-DIMENSION",
  "L4-COMPONENT",
  "L5- MATERIAL",
  "L6-STD",
  "L8 -ITEM CATEGORY",
  "RECEIVED QTY.",
  "DISPATCH QTY.",
  "AVAILABLE QTY.",
  "REMARKS",
  "sum of PHYSICAL stock",
  "stock as per erp",
  "rate/unit",
  "rate per pc*qty*weight",
  "weight per pc",
  "item wise-value",
  "MOVING WITHIN 3 MONTHS",
  "Order Ag Approval recvd",
  "PURCHASE IN 26-27",
  "dispatched in 26-27",
  "ORDER IN hand QTY",
  "shortage qty",
  "",
  "item type",
  "PRICE",
  "MOQ",
  "IF LESS THAN MOQ- EXTRA CHARGES",
  "DRAWING/ TECHNICAL DATA",
];

export const COL_INDEX_TO_DB_FIELD: Record<number, string> = {
  0: "erp_code",
  1: "location",
  2: "l2_valve_type",
  3: "dimension",
  4: "l7_dimension",
  5: "l4_component",
  6: "l5_material",
  7: "l6_std",
  8: "l8_item_category",
  9: "received_qty",
  10: "dispatch_qty",
  11: "available_qty",
  12: "remarks",
  13: "sum_of_physical_stock",
  14: "stock_as_per_erp",
  15: "rate_unit",
  16: "rate_per_pc_qty_weight",
  17: "weight_per_pc",
  18: "item_wise_value",
  19: "moving_within_3_months",
  20: "order_ag_approval_recvd",
  21: "purchase_in_26_27",
  22: "dispatched_in_26_27",
  23: "order_in_hand_qty",
  24: "shortage_qty",
  25: "unnamed_aa",
  26: "item_type",
  27: "price",
  28: "moq",
  29: "if_less_than_moq_extra_charges",
  30: "drawing_technical_data",
};

export const NUMERIC_COLUMNS = new Set([
  "RECEIVED QTY.",
  "DISPATCH QTY.",
  "AVAILABLE QTY.",
  "sum of PHYSICAL stock",
  "stock as per erp",
  "rate/unit",
  "rate per pc*qty*weight",
  "weight per pc",
  "item wise-value",
  "PURCHASE IN 26-27",
  "dispatched in 26-27",
  "ORDER IN hand QTY",
  "shortage qty",
  "",
]);

export const STATUS_COLUMNS = new Set<string>([]);

export const EDITABLE_COLUMNS = [
  "REMARKS",
  "item type",
  "PRICE",
  "MOQ",
  "IF LESS THAN MOQ- EXTRA CHARGES",
  "DRAWING/ TECHNICAL DATA",
];

export const EDITABLE_FIELDS = EDITABLE_COLUMNS.map(
  (header) => COL_INDEX_TO_DB_FIELD[COLUMNS.indexOf(header)],
).filter(Boolean);